spring.application.name=taskflow-api

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow_db
spring.datasource.username=taskflow_user
spring.datasource.password=Taskflow123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080